package storage

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"
)

// Global is the active Store, pinned once at startup via Init.
//
// A package variable rather than a parameter threaded through every handler: this is the
// third singleton in the repo, for the same reason as GlobalTaskManager and
// GlobalManifestState — turning it into dependency injection would touch every handler
// constructor, and that refactor is worth doing for all three together, not for this one
// alone.
var Global Store

// baseDir is the active storage root, kept for callers that still need the real path.
var baseDir = "storage"

// Init pins the storage backend according to configuration.
//
// An empty or "local" backend uses the local disk. Other names are recognized here so the
// error message states which values are valid, instead of silently falling back to local — a
// mistyped backend that still starts means files land somewhere nobody reads, and that only
// surfaces when someone needs them again.
func Init(backend, dir string, s3cfg S3Config) error {
	switch strings.ToLower(strings.TrimSpace(backend)) {
	case "", "local":
		if dir != "" {
			baseDir = dir
		}
		s, err := NewLocalStore(baseDir)
		if err != nil {
			return fmt.Errorf("failed to initialize local store at %q: %w", baseDir, err)
		}
		Global = s
		log.Printf("Storage: local at %s", s.root)
		return nil

	case "s3":
		// Deadline for the startup bucket check. A timeout turns a misaddressed endpoint
		// into a clear error instead of a hung process with no indication of what it is
		// waiting for.
		ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
		defer cancel()

		s, err := NewS3Store(ctx, s3cfg)
		if err != nil {
			return fmt.Errorf("failed to initialize S3 store (bucket %q): %w", s3cfg.Bucket, err)
		}
		Global = s

		where := s3cfg.Endpoint
		if where == "" {
			where = "AWS " + s3cfg.Region
		}
		auth := "IAM role"
		if s3cfg.AccessKey != "" {
			auth = "static key"
		}
		log.Printf("Storage: S3 bucket %q at %s (%s)", s3cfg.Bucket, where, auth)
		return nil

	default:
		return fmt.Errorf("STORAGE_BACKEND=%q is invalid; only \"local\" or \"s3\" are accepted", backend)
	}
}

// AudioKey is the key of the generated output audio for a task.
func AudioKey(taskID, format string) string {
	return "audio/" + safeSegment(taskID) + "." + safeSegment(format)
}

// TempKey is the key of a temporary audio file (e.g. reference file uploaded for zero-shot clone).
func TempKey(filename string) string {
	return "temp/" + safeSegment(filename)
}

// TranscodeKey is the key of a transcoded version, stored in the output audio branch.
func TranscodeKey(taskID, format string) string {
	return "audio/" + safeSegment(taskID) + ".to." + safeSegment(format)
}

// VoiceKey is the key of a saved user reference voice file, separated by mode then user.
func VoiceKey(modeID, userID, filename string) string {
	return safeSegment(modeID) + "/" + safeSegment(userID) + "/voice/" + safeSegment(filename)
}

// AudioPrefix is the branch containing output audio generated by the engine.
const AudioPrefix = "audio"

// TempPrefix is the branch containing temporary buffer files (zero-shot clone uploads).
const TempPrefix = "temp"

// Root returns the currently active local storage root.
//
// Only used to recognize the prefix in legacy records that stored system paths instead of
// keys. With a non-disk backend, this value does not describe where data actually lives.
func Root() string { return baseDir }

// safeSegment replaces every character outside [A-Za-z0-9._-] with "_", and specially
// handles ".." because it consists only of allowed characters but still traverses up a level.
func safeSegment(s string) string {
	if s == "" || s == "." || s == ".." {
		return "_"
	}
	out := []rune(s)
	for i, r := range out {
		ok := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') ||
			r == '.' || r == '_' || r == '-'
		if !ok {
			out[i] = '_'
		}
	}
	return string(out)
}
