// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/tts.proto

package tts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StandardTTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardTTSRequest) Reset() {
	*x = StandardTTSRequest{}
	mi := &file_proto_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardTTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardTTSRequest) ProtoMessage() {}

func (x *StandardTTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardTTSRequest.ProtoReflect.Descriptor instead.
func (*StandardTTSRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{0}
}

func (x *StandardTTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StandardTTSRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *StandardTTSRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type CloneTTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	RefAudioPath  string                 `protobuf:"bytes,2,opt,name=ref_audio_path,json=refAudioPath,proto3" json:"ref_audio_path,omitempty"`
	RefText       string                 `protobuf:"bytes,3,opt,name=ref_text,json=refText,proto3" json:"ref_text,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneTTSRequest) Reset() {
	*x = CloneTTSRequest{}
	mi := &file_proto_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneTTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneTTSRequest) ProtoMessage() {}

func (x *CloneTTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneTTSRequest.ProtoReflect.Descriptor instead.
func (*CloneTTSRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{1}
}

func (x *CloneTTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CloneTTSRequest) GetRefAudioPath() string {
	if x != nil {
		return x.RefAudioPath
	}
	return ""
}

func (x *CloneTTSRequest) GetRefText() string {
	if x != nil {
		return x.RefText
	}
	return ""
}

func (x *CloneTTSRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type FastTTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Voice         string                 `protobuf:"bytes,2,opt,name=voice,proto3" json:"voice,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FastTTSRequest) Reset() {
	*x = FastTTSRequest{}
	mi := &file_proto_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FastTTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastTTSRequest) ProtoMessage() {}

func (x *FastTTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastTTSRequest.ProtoReflect.Descriptor instead.
func (*FastTTSRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{2}
}

func (x *FastTTSRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *FastTTSRequest) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

func (x *FastTTSRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type TTSChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	AudioBytes    []byte                 `protobuf:"bytes,3,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	AudioPath     string                 `protobuf:"bytes,4,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSChunkResponse) Reset() {
	*x = TTSChunkResponse{}
	mi := &file_proto_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSChunkResponse) ProtoMessage() {}

func (x *TTSChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSChunkResponse.ProtoReflect.Descriptor instead.
func (*TTSChunkResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{3}
}

func (x *TTSChunkResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *TTSChunkResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *TTSChunkResponse) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *TTSChunkResponse) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *TTSChunkResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TTSChunkResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_tts_proto protoreflect.FileDescriptor

const file_proto_tts_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tts.proto\x12\x03tts\"T\n" +
	"\x12StandardTTSRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\"|\n" +
	"\x0fCloneTTSRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12$\n" +
	"\x0eref_audio_path\x18\x02 \x01(\tR\frefAudioPath\x12\x19\n" +
	"\bref_text\x18\x03 \x01(\tR\arefText\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\"P\n" +
	"\x0eFastTTSRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05voice\x18\x02 \x01(\tR\x05voice\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\"\xcb\x01\n" +
	"\x10TTSChunkResponse\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vaudio_bytes\x18\x03 \x01(\fR\n" +
	"audioBytes\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x04 \x01(\tR\taudioPath\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x06 \x01(\tR\berrorMsg2\xd6\x01\n" +
	"\n" +
	"TTSService\x12F\n" +
	"\x12SynthesizeStandard\x12\x17.tts.StandardTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01\x12@\n" +
	"\x0fSynthesizeClone\x12\x14.tts.CloneTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01\x12>\n" +
	"\x0eSynthesizeFast\x12\x13.tts.FastTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01B\x18Z\x16core-backend/proto/ttsb\x06proto3"

var (
	file_proto_tts_proto_rawDescOnce sync.Once
	file_proto_tts_proto_rawDescData []byte
)

func file_proto_tts_proto_rawDescGZIP() []byte {
	file_proto_tts_proto_rawDescOnce.Do(func() {
		file_proto_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)))
	})
	return file_proto_tts_proto_rawDescData
}

var file_proto_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_tts_proto_goTypes = []any{
	(*StandardTTSRequest)(nil), // 0: tts.StandardTTSRequest
	(*CloneTTSRequest)(nil),    // 1: tts.CloneTTSRequest
	(*FastTTSRequest)(nil),     // 2: tts.FastTTSRequest
	(*TTSChunkResponse)(nil),   // 3: tts.TTSChunkResponse
}
var file_proto_tts_proto_depIdxs = []int32{
	0, // 0: tts.TTSService.SynthesizeStandard:input_type -> tts.StandardTTSRequest
	1, // 1: tts.TTSService.SynthesizeClone:input_type -> tts.CloneTTSRequest
	2, // 2: tts.TTSService.SynthesizeFast:input_type -> tts.FastTTSRequest
	3, // 3: tts.TTSService.SynthesizeStandard:output_type -> tts.TTSChunkResponse
	3, // 4: tts.TTSService.SynthesizeClone:output_type -> tts.TTSChunkResponse
	3, // 5: tts.TTSService.SynthesizeFast:output_type -> tts.TTSChunkResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_tts_proto_init() }
func file_proto_tts_proto_init() {
	if File_proto_tts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tts_proto_goTypes,
		DependencyIndexes: file_proto_tts_proto_depIdxs,
		MessageInfos:      file_proto_tts_proto_msgTypes,
	}.Build()
	File_proto_tts_proto = out.File
	file_proto_tts_proto_goTypes = nil
	file_proto_tts_proto_depIdxs = nil
}
