// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/tts.proto

package tts

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TTSService_SynthesizeStandard_FullMethodName = "/tts.TTSService/SynthesizeStandard"
	TTSService_SynthesizeClone_FullMethodName    = "/tts.TTSService/SynthesizeClone"
	TTSService_SynthesizeFast_FullMethodName     = "/tts.TTSService/SynthesizeFast"
)

// TTSServiceClient is the client API for TTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service giao tiếp TTS cao cấp giữa Go Core-Backend và Python Core-TTS Engine
type TTSServiceClient interface {
	// SynthesizeStandard stream các đoạn audio tổng hợp chuẩn theo thời gian thực (Server Streaming)
	SynthesizeStandard(ctx context.Context, in *StandardTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error)
	// SynthesizeClone stream các đoạn audio nhân bản giọng nói (Voice Cloning) thời gian thực
	SynthesizeClone(ctx context.Context, in *CloneTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error)
	// SynthesizeFast stream các đoạn audio tốc độ cao (Fast Engine) thời gian thực
	SynthesizeFast(ctx context.Context, in *FastTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error)
}

type tTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTTSServiceClient(cc grpc.ClientConnInterface) TTSServiceClient {
	return &tTSServiceClient{cc}
}

func (c *tTSServiceClient) SynthesizeStandard(ctx context.Context, in *StandardTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[0], TTSService_SynthesizeStandard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StandardTTSRequest, TTSChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeStandardClient = grpc.ServerStreamingClient[TTSChunkResponse]

func (c *tTSServiceClient) SynthesizeClone(ctx context.Context, in *CloneTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[1], TTSService_SynthesizeClone_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CloneTTSRequest, TTSChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeCloneClient = grpc.ServerStreamingClient[TTSChunkResponse]

func (c *tTSServiceClient) SynthesizeFast(ctx context.Context, in *FastTTSRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TTSChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TTSService_ServiceDesc.Streams[2], TTSService_SynthesizeFast_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FastTTSRequest, TTSChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeFastClient = grpc.ServerStreamingClient[TTSChunkResponse]

// TTSServiceServer is the server API for TTSService service.
// All implementations must embed UnimplementedTTSServiceServer
// for forward compatibility.
//
// Service giao tiếp TTS cao cấp giữa Go Core-Backend và Python Core-TTS Engine
type TTSServiceServer interface {
	// SynthesizeStandard stream các đoạn audio tổng hợp chuẩn theo thời gian thực (Server Streaming)
	SynthesizeStandard(*StandardTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error
	// SynthesizeClone stream các đoạn audio nhân bản giọng nói (Voice Cloning) thời gian thực
	SynthesizeClone(*CloneTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error
	// SynthesizeFast stream các đoạn audio tốc độ cao (Fast Engine) thời gian thực
	SynthesizeFast(*FastTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error
	mustEmbedUnimplementedTTSServiceServer()
}

// UnimplementedTTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTTSServiceServer struct{}

func (UnimplementedTTSServiceServer) SynthesizeStandard(*StandardTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method SynthesizeStandard not implemented")
}
func (UnimplementedTTSServiceServer) SynthesizeClone(*CloneTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method SynthesizeClone not implemented")
}
func (UnimplementedTTSServiceServer) SynthesizeFast(*FastTTSRequest, grpc.ServerStreamingServer[TTSChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method SynthesizeFast not implemented")
}
func (UnimplementedTTSServiceServer) mustEmbedUnimplementedTTSServiceServer() {}
func (UnimplementedTTSServiceServer) testEmbeddedByValue()                    {}

// UnsafeTTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TTSServiceServer will
// result in compilation errors.
type UnsafeTTSServiceServer interface {
	mustEmbedUnimplementedTTSServiceServer()
}

func RegisterTTSServiceServer(s grpc.ServiceRegistrar, srv TTSServiceServer) {
	// If the following call panics, it indicates UnimplementedTTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TTSService_ServiceDesc, srv)
}

func _TTSService_SynthesizeStandard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StandardTTSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServiceServer).SynthesizeStandard(m, &grpc.GenericServerStream[StandardTTSRequest, TTSChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeStandardServer = grpc.ServerStreamingServer[TTSChunkResponse]

func _TTSService_SynthesizeClone_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CloneTTSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServiceServer).SynthesizeClone(m, &grpc.GenericServerStream[CloneTTSRequest, TTSChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeCloneServer = grpc.ServerStreamingServer[TTSChunkResponse]

func _TTSService_SynthesizeFast_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FastTTSRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TTSServiceServer).SynthesizeFast(m, &grpc.GenericServerStream[FastTTSRequest, TTSChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TTSService_SynthesizeFastServer = grpc.ServerStreamingServer[TTSChunkResponse]

// TTSService_ServiceDesc is the grpc.ServiceDesc for TTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tts.TTSService",
	HandlerType: (*TTSServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SynthesizeStandard",
			Handler:       _TTSService_SynthesizeStandard_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeClone",
			Handler:       _TTSService_SynthesizeClone_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SynthesizeFast",
			Handler:       _TTSService_SynthesizeFast_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/tts.proto",
}
