replicaCount: 1

image:
  repository: harbor.amoratran.id.vn/tiny-src/vieneu-tts-api
  pullPolicy: Always
  tag: "8f6131e347ec0ecec72d774368f75c58d7d26a3b"

imagePullSecrets:
  - name: tiny-src-registry-secret
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/proxy-body-size: "0"
    # Tắt Basic Auth Traefik vì Web App đã tích hợp hệ thống đăng nhập JWT riêng
    # traefik.ingress.kubernetes.io/router.middlewares: tiny-src-tts-vieneu-tts-api-auth@kubernetescrd
  hosts:
    - host: tts.amoratran.id.vn
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "4"
    memory: "8Gi"

persistence:
  enabled: true
  storageClass: "local-path"
  accessMode: "ReadWriteOnce"
  size: "10Gi"
  mountPath: "/root/.cache"

nodeSelector: {}
tolerations: []
affinity: {}
