// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/tts.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestJson  string                 `protobuf:"bytes,1,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"` // Full UniversalManifest as JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetManifestJson() string {
	if x != nil {
		return x.ManifestJson
	}
	return ""
}

type GetVoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       *string                `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3,oneof" json:"model_id,omitempty"` // Filter by mode, e.g. "fast", "standard"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoicesRequest) Reset() {
	*x = GetVoicesRequest{}
	mi := &file_proto_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoicesRequest) ProtoMessage() {}

func (x *GetVoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoicesRequest.ProtoReflect.Descriptor instead.
func (*GetVoicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{2}
}

func (x *GetVoicesRequest) GetModelId() string {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return ""
}

type VoiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Descriptions  []string               `protobuf:"bytes,3,rep,name=descriptions,proto3" json:"descriptions,omitempty"`
	Modes         []string               `protobuf:"bytes,4,rep,name=modes,proto3" json:"modes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceInfo) Reset() {
	*x = VoiceInfo{}
	mi := &file_proto_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceInfo) ProtoMessage() {}

func (x *VoiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceInfo.ProtoReflect.Descriptor instead.
func (*VoiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{3}
}

func (x *VoiceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VoiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VoiceInfo) GetDescriptions() []string {
	if x != nil {
		return x.Descriptions
	}
	return nil
}

func (x *VoiceInfo) GetModes() []string {
	if x != nil {
		return x.Modes
	}
	return nil
}

type GetVoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voices        []*VoiceInfo           `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVoicesResponse) Reset() {
	*x = GetVoicesResponse{}
	mi := &file_proto_tts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVoicesResponse) ProtoMessage() {}

func (x *GetVoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVoicesResponse.ProtoReflect.Descriptor instead.
func (*GetVoicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{4}
}

func (x *GetVoicesResponse) GetVoices() []*VoiceInfo {
	if x != nil {
		return x.Voices
	}
	return nil
}

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	VoiceId       string                 `protobuf:"bytes,2,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	Speed         float64                `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"` // "standard" | "fast" | "zero_shot_clone"
	Pitch         *float64               `protobuf:"fixed64,5,opt,name=pitch,proto3,oneof" json:"pitch,omitempty"`
	Emotion       *string                `protobuf:"bytes,6,opt,name=emotion,proto3,oneof" json:"emotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_proto_tts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{5}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *SynthesizeRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SynthesizeRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SynthesizeRequest) GetPitch() float64 {
	if x != nil && x.Pitch != nil {
		return *x.Pitch
	}
	return 0
}

func (x *SynthesizeRequest) GetEmotion() string {
	if x != nil && x.Emotion != nil {
		return *x.Emotion
	}
	return ""
}

type SynthesizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioBytes    []byte                 `protobuf:"bytes,1,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeResponse) Reset() {
	*x = SynthesizeResponse{}
	mi := &file_proto_tts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeResponse) ProtoMessage() {}

func (x *SynthesizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeResponse.ProtoReflect.Descriptor instead.
func (*SynthesizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{6}
}

func (x *SynthesizeResponse) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *SynthesizeResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type CloneVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioBytes    []byte                 `protobuf:"bytes,1,opt,name=audio_bytes,json=audioBytes,proto3" json:"audio_bytes,omitempty"` // Reference audio file content
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // User-provided name for the cloned voice
	Engine        string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`                           // Mode, e.g. "zero_shot_clone"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneVoiceRequest) Reset() {
	*x = CloneVoiceRequest{}
	mi := &file_proto_tts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneVoiceRequest) ProtoMessage() {}

func (x *CloneVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneVoiceRequest.ProtoReflect.Descriptor instead.
func (*CloneVoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{7}
}

func (x *CloneVoiceRequest) GetAudioBytes() []byte {
	if x != nil {
		return x.AudioBytes
	}
	return nil
}

func (x *CloneVoiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloneVoiceRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type CloneVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceId       string                 `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "success" | "error"
	ErrorMsg      string                 `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloneVoiceResponse) Reset() {
	*x = CloneVoiceResponse{}
	mi := &file_proto_tts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneVoiceResponse) ProtoMessage() {}

func (x *CloneVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloneVoiceResponse.ProtoReflect.Descriptor instead.
func (*CloneVoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{8}
}

func (x *CloneVoiceResponse) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *CloneVoiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloneVoiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CloneVoiceResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_tts_proto protoreflect.FileDescriptor

const file_proto_tts_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tts.proto\x12\x03tts\"\x10\n" +
	"\x0eGetInfoRequest\"6\n" +
	"\x0fGetInfoResponse\x12#\n" +
	"\rmanifest_json\x18\x01 \x01(\tR\fmanifestJson\"?\n" +
	"\x10GetVoicesRequest\x12\x1e\n" +
	"\bmodel_id\x18\x01 \x01(\tH\x00R\amodelId\x88\x01\x01B\v\n" +
	"\t_model_id\"i\n" +
	"\tVoiceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\fdescriptions\x18\x03 \x03(\tR\fdescriptions\x12\x14\n" +
	"\x05modes\x18\x04 \x03(\tR\x05modes\";\n" +
	"\x11GetVoicesResponse\x12&\n" +
	"\x06voices\x18\x01 \x03(\v2\x0e.tts.VoiceInfoR\x06voices\"\xc0\x01\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bvoice_id\x18\x02 \x01(\tR\avoiceId\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x01R\x05speed\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x19\n" +
	"\x05pitch\x18\x05 \x01(\x01H\x00R\x05pitch\x88\x01\x01\x12\x1d\n" +
	"\aemotion\x18\x06 \x01(\tH\x01R\aemotion\x88\x01\x01B\b\n" +
	"\x06_pitchB\n" +
	"\n" +
	"\b_emotion\"R\n" +
	"\x12SynthesizeResponse\x12\x1f\n" +
	"\vaudio_bytes\x18\x01 \x01(\fR\n" +
	"audioBytes\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\"`\n" +
	"\x11CloneVoiceRequest\x12\x1f\n" +
	"\vaudio_bytes\x18\x01 \x01(\fR\n" +
	"audioBytes\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\"x\n" +
	"\x12CloneVoiceResponse\x12\x19\n" +
	"\bvoice_id\x18\x01 \x01(\tR\avoiceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\terror_msg\x18\x04 \x01(\tR\berrorMsg2\xfc\x01\n" +
	"\n" +
	"TTSService\x124\n" +
	"\aGetInfo\x12\x13.tts.GetInfoRequest\x1a\x14.tts.GetInfoResponse\x12:\n" +
	"\tGetVoices\x12\x15.tts.GetVoicesRequest\x1a\x16.tts.GetVoicesResponse\x12=\n" +
	"\n" +
	"Synthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse\x12=\n" +
	"\n" +
	"CloneVoice\x12\x16.tts.CloneVoiceRequest\x1a\x17.tts.CloneVoiceResponseB\x0fZ\rbackend/protob\x06proto3"

var (
	file_proto_tts_proto_rawDescOnce sync.Once
	file_proto_tts_proto_rawDescData []byte
)

func file_proto_tts_proto_rawDescGZIP() []byte {
	file_proto_tts_proto_rawDescOnce.Do(func() {
		file_proto_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)))
	})
	return file_proto_tts_proto_rawDescData
}

var file_proto_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_tts_proto_goTypes = []any{
	(*GetInfoRequest)(nil),     // 0: tts.GetInfoRequest
	(*GetInfoResponse)(nil),    // 1: tts.GetInfoResponse
	(*GetVoicesRequest)(nil),   // 2: tts.GetVoicesRequest
	(*VoiceInfo)(nil),          // 3: tts.VoiceInfo
	(*GetVoicesResponse)(nil),  // 4: tts.GetVoicesResponse
	(*SynthesizeRequest)(nil),  // 5: tts.SynthesizeRequest
	(*SynthesizeResponse)(nil), // 6: tts.SynthesizeResponse
	(*CloneVoiceRequest)(nil),  // 7: tts.CloneVoiceRequest
	(*CloneVoiceResponse)(nil), // 8: tts.CloneVoiceResponse
}
var file_proto_tts_proto_depIdxs = []int32{
	3, // 0: tts.GetVoicesResponse.voices:type_name -> tts.VoiceInfo
	0, // 1: tts.TTSService.GetInfo:input_type -> tts.GetInfoRequest
	2, // 2: tts.TTSService.GetVoices:input_type -> tts.GetVoicesRequest
	5, // 3: tts.TTSService.Synthesize:input_type -> tts.SynthesizeRequest
	7, // 4: tts.TTSService.CloneVoice:input_type -> tts.CloneVoiceRequest
	1, // 5: tts.TTSService.GetInfo:output_type -> tts.GetInfoResponse
	4, // 6: tts.TTSService.GetVoices:output_type -> tts.GetVoicesResponse
	6, // 7: tts.TTSService.Synthesize:output_type -> tts.SynthesizeResponse
	8, // 8: tts.TTSService.CloneVoice:output_type -> tts.CloneVoiceResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tts_proto_init() }
func file_proto_tts_proto_init() {
	if File_proto_tts_proto != nil {
		return
	}
	file_proto_tts_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_tts_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tts_proto_goTypes,
		DependencyIndexes: file_proto_tts_proto_depIdxs,
		MessageInfos:      file_proto_tts_proto_msgTypes,
	}.Build()
	File_proto_tts_proto = out.File
	file_proto_tts_proto_goTypes = nil
	file_proto_tts_proto_depIdxs = nil
}
