-- PostgreSQL DDL Schema for VieNeu Core Backend

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(64) PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    is_approved BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_voices (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    model_id VARCHAR(50) NOT NULL DEFAULT 'clone',
    name VARCHAR(255) NOT NULL,
    gender VARCHAR(50),
    region VARCHAR(50),
    style VARCHAR(50),
    file_path VARCHAR(512) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tts_jobs (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    engine VARCHAR(50) NOT NULL,
    voice VARCHAR(255) NOT NULL,
    speed DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    pitch DOUBLE PRECISION,
    emotion VARCHAR(50),
    total_chunks INT NOT NULL DEFAULT 1,
    text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tts_chunks (
    id VARCHAR(64) PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL REFERENCES tts_jobs(id) ON DELETE CASCADE,
    chunk_index INT NOT NULL DEFAULT 0,
    text TEXT NOT NULL DEFAULT '',
    audio_path VARCHAR(512),
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    error_msg TEXT
);
