package db

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"log"
	"time"

	"backend/config"
	"backend/db/sqlc"
	"backend/security"

	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	"github.com/golang-migrate/migrate/v4/source/iofs"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

var (
	// Pool manages the high-performance PostgreSQL Connection Pool from pgx.
	Pool *pgxpool.Pool

	// Queries holds type-safe database query methods auto-generated by sqlc.
	Queries *sqlc.Queries
)

// InitOptions selects which initialization steps NOT every process should run.
//
// Connecting the pool is needed by every process. Migrations and seed accounts are not: they
// mutate shared state, so letting each process run them means N processes racing to do a job
// that only needs doing once. golang-migrate has its own lock so data is not corrupted, but the
// loser that times out on the lock kills the whole process — with multiple replicas starting
// together, that is an unexplained restart loop.
type InitOptions struct {
	// Migrate allows this process to apply migrations.
	Migrate bool
	// Seed allows this process to create default accounts.
	Seed bool
}

// InitDB initializes the PostgreSQL database connection with flexible Connection Pool
// configuration, and optionally applies migrations and seed accounts.
func InitDB(cfg *config.Config, opts InitOptions) {
	var pool *pgxpool.Pool
	var err error

	ctx := context.Background()

	// 1. Configure pgxpool from URL and environment variables
	poolConfig, parseErr := pgxpool.ParseConfig(cfg.DatabaseURL)
	if parseErr != nil {
		log.Fatalf("Error parsing DATABASE_URL: %v", parseErr)
	}

	poolConfig.MaxConns = cfg.DBMaxConns
	poolConfig.MinConns = cfg.DBMinConns
	poolConfig.MaxConnLifetime = time.Duration(cfg.DBMaxConnLifetimeMinutes) * time.Minute
	poolConfig.MaxConnIdleTime = time.Duration(cfg.DBMaxConnIdleMinutes) * time.Minute

	maxRetries := cfg.DBConnectMaxRetries
	retryInterval := time.Duration(cfg.DBConnectRetryIntervalSec) * time.Second

	// 2. Connect to PostgreSQL with retry mechanism
	//
	// lastErr preserves the REAL cause of the final attempt. Previously the loop only remembered
	// the error from pgxpool.NewWithConfig and discarded the error from Ping — but NewWithConfig
	// almost always succeeds (it only builds the pool, doesn't connect yet), so every actual
	// failure came from Ping and the final message printed "<nil>". Wrong password, wrong database
	// name, or server refusing connections all looked the same: a line that said nothing.
	// Diagnosis required reading Postgres's own logs.
	for i := 1; i <= maxRetries; i++ {
		log.Printf("Connecting to PostgreSQL pool [MaxConns: %d, MinConns: %d] (Attempt %d/%d)...",
			cfg.DBMaxConns, cfg.DBMinConns, i, maxRetries)

		var lastErr error
		pool, err = pgxpool.NewWithConfig(ctx, poolConfig)
		if err != nil {
			lastErr = fmt.Errorf("building pool: %w", err)
		} else if pingErr := pool.Ping(ctx); pingErr != nil {
			lastErr = fmt.Errorf("ping: %w", pingErr)
			pool.Close()
		} else {
			log.Printf("Successfully connected to PostgreSQL via pgxpool (MaxConns: %d, MinConns: %d)!", cfg.DBMaxConns, cfg.DBMinConns)
			break
		}

		log.Printf("  could not connect: %v", lastErr)

		if i == maxRetries {
			log.Fatalf("Failed to connect to PostgreSQL after %d attempts: %v", maxRetries, lastErr)
		}
		time.Sleep(retryInterval)
	}

	// 3. Versioned migrations via golang-migrate, if this process is assigned that task.
	if opts.Migrate {
		runDatabaseMigrations(cfg.DatabaseURL)
	} else {
		// Say it out loud instead of silently skipping: an operator seeing a schema mismatch needs
		// to know immediately that this process is not the one applying migrations.
		log.Println("Skipping migrations: this process is not assigned that task.")
	}

	Pool = pool
	Queries = sqlc.New(pool)

	// 4. Seed default admin account
	if opts.Seed {
		seedDefaultAccounts(ctx, cfg)
	}
	log.Println("Database initialization completed successfully (SQL-First sqlc & golang-migrate).")
}

// runDatabaseMigrations executes the database schema versioning system (golang-migrate).
//
// Failure is a stop, not a warning. Previously every error branch here only logged "Warning"
// and returned, and InitDB continued serving requests on a schema that might be missing
// columns — manifesting as scattered query errors at individual handlers, far from the real
// failure site. Every other startup condition in this process (manifest, required variables,
// store connection) is fail-closed; this was the only one that diverged, and schema is not
// something worth guessing at.
func runDatabaseMigrations(dbURL string) {
	log.Println("Executing database versioned migrations (golang-migrate)...")

	driver, err := iofs.New(migrationFS, "migrations")
	if err != nil {
		log.Fatalf("Failed to read embedded migration files: %v", err)
	}

	m, err := migrate.NewWithSourceInstance("iofs", driver, dbURL)
	if err != nil {
		log.Fatalf("Failed to initialize golang-migrate: %v", err)
	}
	// migrate opens its own database/sql connections, separate from pgxpool. Not closing them
	// means each process permanently holds an extra connection plus the migration lock session.
	defer func() {
		if srcErr, dbErr := m.Close(); srcErr != nil || dbErr != nil {
			log.Printf("Closing golang-migrate: source=%v db=%v", srcErr, dbErr)
		}
	}()

	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		log.Fatalf("Failed to apply migrations: %v", err)
	}
	log.Println("Database migrations applied successfully (Schema up-to-date)!")
}

// seedDefaultAccounts automatically creates a default Admin account if it does not
// already exist in PostgreSQL.
func seedDefaultAccounts(ctx context.Context, cfg *config.Config) {
	type account struct {
		username string
		password string
		role     string
	}

	accounts := []account{}
	if cfg.DefaultAdminUsername != "" && cfg.DefaultAdminPassword != "" {
		accounts = append(accounts, account{
			username: cfg.DefaultAdminUsername,
			password: cfg.DefaultAdminPassword,
			role:     "admin",
		})
	}


	for _, acc := range accounts {
		_, err := Queries.GetUserByUsername(ctx, acc.username)
		if err != nil {
			hashedPw, err := security.HashPassword(acc.password)
			if err != nil {
				log.Printf("Error hashing password for %s: %v", acc.username, err)
				continue
			}

			userID := uuid.NewString()
			_, err = Queries.CreateUser(ctx, sqlc.CreateUserParams{
				ID:           userID,
				Username:     acc.username,
				PasswordHash: hashedPw,
				Role:         acc.role,
				IsApproved:   true,
			})
			if err != nil {
				log.Printf("Error creating default account %s: %v", acc.username, err)
			} else {
				log.Printf("Created default %s account: %s", acc.role, acc.username)
			}
		} else {
			log.Printf("Account '%s' already exists.", acc.username)
		}
	}
}

// RegisterJobAndChunk registers or updates a large TTS Job along with its child Chunk in
// PostgreSQL via sqlc. JobAudioParams groups the voice control parameters that the Manifest
// may enable/disable per Engine. Pitch/Emotion use pointers to distinguish "engine does not
// support" (nil) from a value the user actually chose (e.g. pitch = 0 is a valid neutral).
type JobAudioParams struct {
	Speed   float64
	Pitch   *float64
	Emotion *string
}

// PitchColumn converts Pitch to a nullable PostgreSQL column.
func (p JobAudioParams) PitchColumn() pgtype.Float8 {
	if p.Pitch == nil {
		return pgtype.Float8{}
	}
	return pgtype.Float8{Float64: *p.Pitch, Valid: true}
}

// EmotionColumn converts Emotion to a nullable PostgreSQL column.
func (p JobAudioParams) EmotionColumn() pgtype.Text {
	if p.Emotion == nil || *p.Emotion == "" {
		return pgtype.Text{}
	}
	return pgtype.Text{String: *p.Emotion, Valid: true}
}

// ErrJobNotOwned means the submitted job_id belongs to someone else.
//
// A separate error type so the handler returns 403 instead of 500: this is a rejected request,
// not a system failure.
var ErrJobNotOwned = errors.New("db: job belongs to a different user")

func RegisterJobAndChunk(ctx context.Context, userID, jobID, engine, voice string, audio JobAudioParams, totalChunks int, taskID string, chunkIndex int, text string) error {
	// One statement instead of read-then-write: the first two chunks of the same job arriving
	// in parallel both see the job as not existing and both insert, and the loser is silently
	// dropped. This is on the hot path of every chunk so one fewer round-trip is less latency
	// the user sees.
	owner, err := Queries.EnsureTTSJob(ctx, sqlc.EnsureTTSJobParams{
		ID:          jobID,
		UserID:      userID,
		Engine:      engine,
		Voice:       voice,
		Speed:       audio.Speed,
		Pitch:       audio.PitchColumn(),
		Emotion:     audio.EmotionColumn(),
		TotalChunks: int32(totalChunks),
		Text:        text,
	})
	if err != nil {
		return err
	}

	// job_id is submitted by the client and nothing guarantees it belongs to the caller. Without
	// checking here, one person could insert a chunk — with their own text — into someone else's
	// job, and that segment would appear in the other person's history. The owner comes from the
	// same statement above, so no extra round-trip.
	if owner != userID {
		return ErrJobNotOwned
	}

	_, err = Queries.CreateTTSChunk(ctx, sqlc.CreateTTSChunkParams{
		ID:         taskID,
		JobID:      jobID,
		ChunkIndex: int32(chunkIndex),
		Text:       text,
		Status:     "pending",
	})
	return err
}

// UpdateChunkStatus updates the progress status (processing, done, error), audio file path, or
// error message of a Chunk.
func UpdateChunkStatus(ctx context.Context, taskID, status string, audioPath *string, errorMsg *string) error {
	params := sqlc.UpdateTTSChunkStatusParams{
		ID:     taskID,
		Status: status,
	}
	if audioPath != nil {
		params.AudioPath = pgtype.Text{String: *audioPath, Valid: true}
	}
	if errorMsg != nil {
		params.ErrorMsg = pgtype.Text{String: *errorMsg, Valid: true}
	}
	_, err := Queries.UpdateTTSChunkStatus(ctx, params)
	return err
}

// CancelChunk transitions a chunk still in pending/processing to 'cancelled' at the moment of
// cancellation.
//
// Separate from UpdateChunkStatus because this is a conditional write: only transitions from
// pending/processing so it does not overwrite the result if the worker won the race and already
// wrote 'done'/'error'. Returns the number of rows actually changed, used for logging. This DB
// write is in the CancelTask handler, not waiting for the worker: a job still queued has no one
// else who will set the chunk to 'cancelled'.
func CancelChunk(ctx context.Context, taskID string) (int64, error) {
	// Handler tests that cancel tasks run without a DB (Queries = nil): the DB write is optional,
	// silently skip instead of nil panic. Production always has Queries after InitDB so this
	// branch never runs.
	if Queries == nil {
		return 0, nil
	}
	return Queries.CancelTTSChunk(ctx, taskID)
}
