{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vieneu-tts-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vieneu-tts-api.name" . }}
    helm.sh/chart: {{ include "vieneu-tts-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ include "vieneu-tts-api.fullname" . }}-tls
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "vieneu-tts-api.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
{{- end }}
