apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ui-studio.fullname" . }}-auth
  namespace: {{ .Values.namespace | default "ui-studio" }}
  labels:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}
    helm.sh/chart: {{ include "ui-studio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  basicAuth:
    secret: studio-auth-secret
