{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ui-studio.fullname" . }}-ingress
  namespace: {{ .Values.namespace | default "ui-studio" }}
  labels:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}
    helm.sh/chart: {{ include "ui-studio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "ui-studio.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui-studio.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /storage
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui-studio.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ui-studio.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
