apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "ui-studio" }}
  labels:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
