apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | default "vieneu-studio" }}
  labels:
    app.kubernetes.io/name: {{ include "better-tts-studio.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
