{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui-studio.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}-redis
    helm.sh/chart: {{ include "ui-studio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ui-studio.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ui-studio.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ui-studio.fullname" . }}-secret
                  key: redisPassword
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui-studio.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}-redis
    helm.sh/chart: {{ include "ui-studio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "ui-studio.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}