// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTTSChunk = `-- name: CancelTTSChunk :execrows
UPDATE tts_chunks
SET status = 'cancelled',
    error_msg = COALESCE(error_msg, 'Đã huỷ theo yêu cầu'),
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'processing')
`

// Chuyển chunk còn đang chờ/xử lý sang 'cancelled'. Guard bằng status để cancel chạy đua với
// worker hoàn tất không đè được kết quả: chunk đã 'done'/'error' giữ nguyên trạng thái.
func (q *Queries) CancelTTSChunk(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelTTSChunk, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTTSChunk = `-- name: CreateTTSChunk :one
INSERT INTO tts_chunks (id, job_id, chunk_index, text, audio_path, status, error_msg)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at
`

type CreateTTSChunkParams struct {
	ID         string      `json:"id"`
	JobID      string      `json:"job_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Text       string      `json:"text"`
	AudioPath  pgtype.Text `json:"audio_path"`
	Status     string      `json:"status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

func (q *Queries) CreateTTSChunk(ctx context.Context, arg CreateTTSChunkParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, createTTSChunk,
		arg.ID,
		arg.JobID,
		arg.ChunkIndex,
		arg.Text,
		arg.AudioPath,
		arg.Status,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskOwner = `-- name: GetTaskOwner :one
SELECT j.user_id FROM tts_chunks c
JOIN tts_jobs j ON j.id = c.job_id
WHERE c.id = $1
`

func (q *Queries) GetTaskOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTaskOwner, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const listTTSChunksByJobID = `-- name: ListTTSChunksByJobID :many
SELECT id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at FROM tts_chunks
WHERE job_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListTTSChunksByJobID(ctx context.Context, jobID string) ([]TtsChunk, error) {
	rows, err := q.db.Query(ctx, listTTSChunksByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsChunk{}
	for rows.Next() {
		var i TtsChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ChunkIndex,
			&i.Text,
			&i.AudioPath,
			&i.Status,
			&i.ErrorMsg,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStaleChunks = `-- name: ReconcileStaleChunks :execrows
UPDATE tts_chunks
SET status = 'error',
    error_msg = COALESCE(error_msg, 'Job mất sau khi Redis khởi động lại, không phục hồi được'),
    updated_at = now()
WHERE status IN ('pending', 'processing')
  AND updated_at < $1::timestamptz
`

// Chuyển chunk mồ côi về 'error'. Một chunk đứng mãi ở pending/processing nghĩa là không ai
// đang xử lý nó nữa — người điều hành thấy nó kẹt vĩnh viễn sau khi hàng đợi mất (Redis restart:
// stream non-persistent, job trong đó trôi thẳng, không gì phục hồi lại được).
//
// updated_at là mốc tiến triển cuối (CreateTTSChunk đến 'processing' chính là cột mốc bắt đầu);
// tham số $1 là mốc thời gian giới hạn: chunk chưa chuyển trạng thái kể từ trước mốc đó là kẹt.
// Ngưỡng này do STALE_CHUNK_AFTER_MINUTES quyết định và phải lớn hơn thời gian tối đa một
// chunk hợp lệ có thể chạy (từng chunk ≤ TTS_CLIENT_TIMEOUT_SECONDS + chờ queue).
func (q *Queries) ReconcileStaleChunks(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileStaleChunks, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTTSChunkStatus = `-- name: UpdateTTSChunkStatus :one
UPDATE tts_chunks
SET status = $2,
    audio_path = COALESCE($3, audio_path),
    error_msg = COALESCE($4, error_msg),
    updated_at = now()
WHERE id = $1
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at
`

type UpdateTTSChunkStatusParams struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	AudioPath pgtype.Text `json:"audio_path"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateTTSChunkStatus(ctx context.Context, arg UpdateTTSChunkStatusParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, updateTTSChunkStatus,
		arg.ID,
		arg.Status,
		arg.AudioPath,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
		&i.UpdatedAt,
	)
	return i, err
}
