// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTTSChunk = `-- name: CreateTTSChunk :one
INSERT INTO tts_chunks (id, job_id, chunk_index, text, audio_path, status, error_msg)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg
`

type CreateTTSChunkParams struct {
	ID         string      `json:"id"`
	JobID      string      `json:"job_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Text       string      `json:"text"`
	AudioPath  pgtype.Text `json:"audio_path"`
	Status     string      `json:"status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

func (q *Queries) CreateTTSChunk(ctx context.Context, arg CreateTTSChunkParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, createTTSChunk,
		arg.ID,
		arg.JobID,
		arg.ChunkIndex,
		arg.Text,
		arg.AudioPath,
		arg.Status,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
	)
	return i, err
}

const getTaskOwner = `-- name: GetTaskOwner :one
SELECT j.user_id FROM tts_chunks c
JOIN tts_jobs j ON j.id = c.job_id
WHERE c.id = $1
`

func (q *Queries) GetTaskOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTaskOwner, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const listTTSChunksByJobID = `-- name: ListTTSChunksByJobID :many
SELECT id, job_id, chunk_index, text, audio_path, status, error_msg FROM tts_chunks
WHERE job_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListTTSChunksByJobID(ctx context.Context, jobID string) ([]TtsChunk, error) {
	rows, err := q.db.Query(ctx, listTTSChunksByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsChunk{}
	for rows.Next() {
		var i TtsChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ChunkIndex,
			&i.Text,
			&i.AudioPath,
			&i.Status,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTTSChunkStatus = `-- name: UpdateTTSChunkStatus :one
UPDATE tts_chunks
SET status = $2,
    audio_path = COALESCE($3, audio_path),
    error_msg = COALESCE($4, error_msg)
WHERE id = $1
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg
`

type UpdateTTSChunkStatusParams struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	AudioPath pgtype.Text `json:"audio_path"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateTTSChunkStatus(ctx context.Context, arg UpdateTTSChunkStatusParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, updateTTSChunkStatus,
		arg.ID,
		arg.Status,
		arg.AudioPath,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
	)
	return i, err
}
