// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"
)

const createTTSJob = `-- name: CreateTTSJob :one
INSERT INTO tts_jobs (id, user_id, engine, voice, speed, total_chunks, text)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, engine, voice, speed, total_chunks, text, created_at
`

type CreateTTSJobParams struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	Engine      string  `json:"engine"`
	Voice       string  `json:"voice"`
	Speed       float64 `json:"speed"`
	TotalChunks int32   `json:"total_chunks"`
	Text        string  `json:"text"`
}

func (q *Queries) CreateTTSJob(ctx context.Context, arg CreateTTSJobParams) (TtsJob, error) {
	row := q.db.QueryRow(ctx, createTTSJob,
		arg.ID,
		arg.UserID,
		arg.Engine,
		arg.Voice,
		arg.Speed,
		arg.TotalChunks,
		arg.Text,
	)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getTTSJobByID = `-- name: GetTTSJobByID :one
SELECT id, user_id, engine, voice, speed, total_chunks, text, created_at FROM tts_jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTTSJobByID(ctx context.Context, id string) (TtsJob, error) {
	row := q.db.QueryRow(ctx, getTTSJobByID, id)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const getTTSJobByIDAndUser = `-- name: GetTTSJobByIDAndUser :one
SELECT id, user_id, engine, voice, speed, total_chunks, text, created_at FROM tts_jobs
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetTTSJobByIDAndUserParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTTSJobByIDAndUser(ctx context.Context, arg GetTTSJobByIDAndUserParams) (TtsJob, error) {
	row := q.db.QueryRow(ctx, getTTSJobByIDAndUser, arg.ID, arg.UserID)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listAllTTSJobs = `-- name: ListAllTTSJobs :many
SELECT id, user_id, engine, voice, speed, total_chunks, text, created_at FROM tts_jobs
ORDER BY created_at DESC
`

func (q *Queries) ListAllTTSJobs(ctx context.Context) ([]TtsJob, error) {
	rows, err := q.db.Query(ctx, listAllTTSJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsJob{}
	for rows.Next() {
		var i TtsJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Engine,
			&i.Voice,
			&i.Speed,
			&i.TotalChunks,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTTSJobsByUserID = `-- name: ListTTSJobsByUserID :many
SELECT id, user_id, engine, voice, speed, total_chunks, text, created_at FROM tts_jobs
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTTSJobsByUserID(ctx context.Context, userID string) ([]TtsJob, error) {
	rows, err := q.db.Query(ctx, listTTSJobsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsJob{}
	for rows.Next() {
		var i TtsJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Engine,
			&i.Voice,
			&i.Speed,
			&i.TotalChunks,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
