// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TtsChunk struct {
	ID         string      `json:"id"`
	JobID      string      `json:"job_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Text       string      `json:"text"`
	AudioPath  pgtype.Text `json:"audio_path"`
	Status     string      `json:"status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

type TtsJob struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Engine      string             `json:"engine"`
	Voice       string             `json:"voice"`
	Speed       float64            `json:"speed"`
	Pitch       pgtype.Float8      `json:"pitch"`
	Emotion     pgtype.Text        `json:"emotion"`
	TotalChunks int32              `json:"total_chunks"`
	Text        string             `json:"text"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	IsApproved   bool               `json:"is_approved"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserVoice struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ModelID   string             `json:"model_id"`
	Name      string             `json:"name"`
	Gender    pgtype.Text        `json:"gender"`
	Region    pgtype.Text        `json:"region"`
	Style     pgtype.Text        `json:"style"`
	FilePath  string             `json:"file_path"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
