// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserVoice = `-- name: CreateUserVoice :one
INSERT INTO user_voices (id, user_id, name, gender, region, style, file_path)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, gender, region, style, file_path, created_at
`

type CreateUserVoiceParams struct {
	ID       string      `json:"id"`
	UserID   string      `json:"user_id"`
	Name     string      `json:"name"`
	Gender   pgtype.Text `json:"gender"`
	Region   pgtype.Text `json:"region"`
	Style    pgtype.Text `json:"style"`
	FilePath string      `json:"file_path"`
}

func (q *Queries) CreateUserVoice(ctx context.Context, arg CreateUserVoiceParams) (UserVoice, error) {
	row := q.db.QueryRow(ctx, createUserVoice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Gender,
		arg.Region,
		arg.Style,
		arg.FilePath,
	)
	var i UserVoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.Region,
		&i.Style,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserVoice = `-- name: DeleteUserVoice :exec
DELETE FROM user_voices
WHERE id = $1 AND user_id = $2
`

type DeleteUserVoiceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUserVoice(ctx context.Context, arg DeleteUserVoiceParams) error {
	_, err := q.db.Exec(ctx, deleteUserVoice, arg.ID, arg.UserID)
	return err
}

const getUserVoiceByID = `-- name: GetUserVoiceByID :one
SELECT id, user_id, name, gender, region, style, file_path, created_at FROM user_voices
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetUserVoiceByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetUserVoiceByID(ctx context.Context, arg GetUserVoiceByIDParams) (UserVoice, error) {
	row := q.db.QueryRow(ctx, getUserVoiceByID, arg.ID, arg.UserID)
	var i UserVoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.Region,
		&i.Style,
		&i.FilePath,
		&i.CreatedAt,
	)
	return i, err
}

const listUserVoices = `-- name: ListUserVoices :many
SELECT id, user_id, name, gender, region, style, file_path, created_at FROM user_voices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserVoices(ctx context.Context, userID string) ([]UserVoice, error) {
	rows, err := q.db.Query(ctx, listUserVoices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserVoice{}
	for rows.Next() {
		var i UserVoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Gender,
			&i.Region,
			&i.Style,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
