// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelTTSChunk = `-- name: CancelTTSChunk :execrows
UPDATE tts_chunks
SET status = 'cancelled',
    error_msg = COALESCE(error_msg, 'Cancelled by request'),
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'processing')
`

// Transition a pending/processing chunk to 'cancelled'. Guard on status prevents cancel racing with
// worker completion from overwriting the result: a 'done'/'error' chunk keeps its state.
func (q *Queries) CancelTTSChunk(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelTTSChunk, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTTSChunk = `-- name: CreateTTSChunk :one
INSERT INTO tts_chunks (id, job_id, chunk_index, text, audio_path, status, error_msg)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at
`

type CreateTTSChunkParams struct {
	ID         string      `json:"id"`
	JobID      string      `json:"job_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Text       string      `json:"text"`
	AudioPath  pgtype.Text `json:"audio_path"`
	Status     string      `json:"status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

func (q *Queries) CreateTTSChunk(ctx context.Context, arg CreateTTSChunkParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, createTTSChunk,
		arg.ID,
		arg.JobID,
		arg.ChunkIndex,
		arg.Text,
		arg.AudioPath,
		arg.Status,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskOwner = `-- name: GetTaskOwner :one
SELECT j.user_id FROM tts_chunks c
JOIN tts_jobs j ON j.id = c.job_id
WHERE c.id = $1
`

func (q *Queries) GetTaskOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTaskOwner, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const listTTSChunksByJobID = `-- name: ListTTSChunksByJobID :many
SELECT id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at FROM tts_chunks
WHERE job_id = $1
ORDER BY chunk_index ASC
`

func (q *Queries) ListTTSChunksByJobID(ctx context.Context, jobID string) ([]TtsChunk, error) {
	rows, err := q.db.Query(ctx, listTTSChunksByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TtsChunk{}
	for rows.Next() {
		var i TtsChunk
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.ChunkIndex,
			&i.Text,
			&i.AudioPath,
			&i.Status,
			&i.ErrorMsg,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStaleChunks = `-- name: ReconcileStaleChunks :execrows
UPDATE tts_chunks
SET status = 'error',
    error_msg = COALESCE(error_msg, 'Job lost after Redis restart, cannot be recovered'),
    updated_at = now()
WHERE status IN ('pending', 'processing')
  AND updated_at < $1::timestamptz
`

// Transition orphaned chunks to 'error'. A chunk stuck in pending/processing means no one is
// processing it anymore — the operator sees it permanently stuck after the queue is lost (Redis restart:
// non-persistent stream, jobs in it are gone, nothing can recover them).
//
// updated_at is the last progress marker (CreateTTSChunk to 'processing' is the starting point);
// parameter $1 is the cutoff timestamp: a chunk that has not transitioned since before that cutoff is stuck.
// This threshold is determined by STALE_CHUNK_AFTER_MINUTES and must be greater than the maximum time
// a legitimate chunk can run (each chunk ≤ TTS_CLIENT_TIMEOUT_SECONDS + queue wait).
func (q *Queries) ReconcileStaleChunks(ctx context.Context, dollar_1 pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, reconcileStaleChunks, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTTSChunkStatus = `-- name: UpdateTTSChunkStatus :one
UPDATE tts_chunks
SET status = $2,
    audio_path = COALESCE($3, audio_path),
    error_msg = COALESCE($4, error_msg),
    updated_at = now()
WHERE id = $1
RETURNING id, job_id, chunk_index, text, audio_path, status, error_msg, updated_at
`

type UpdateTTSChunkStatusParams struct {
	ID        string      `json:"id"`
	Status    string      `json:"status"`
	AudioPath pgtype.Text `json:"audio_path"`
	ErrorMsg  pgtype.Text `json:"error_msg"`
}

func (q *Queries) UpdateTTSChunkStatus(ctx context.Context, arg UpdateTTSChunkStatusParams) (TtsChunk, error) {
	row := q.db.QueryRow(ctx, updateTTSChunkStatus,
		arg.ID,
		arg.Status,
		arg.AudioPath,
		arg.ErrorMsg,
	)
	var i TtsChunk
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.ChunkIndex,
		&i.Text,
		&i.AudioPath,
		&i.Status,
		&i.ErrorMsg,
		&i.UpdatedAt,
	)
	return i, err
}
