// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTTSJob = `-- name: CreateTTSJob :one
INSERT INTO tts_jobs (id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text, created_at
`

type CreateTTSJobParams struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	Engine      string        `json:"engine"`
	Voice       string        `json:"voice"`
	Speed       float64       `json:"speed"`
	Pitch       pgtype.Float8 `json:"pitch"`
	Emotion     pgtype.Text   `json:"emotion"`
	TotalChunks int32         `json:"total_chunks"`
	Text        string        `json:"text"`
}

func (q *Queries) CreateTTSJob(ctx context.Context, arg CreateTTSJobParams) (TtsJob, error) {
	row := q.db.QueryRow(ctx, createTTSJob,
		arg.ID,
		arg.UserID,
		arg.Engine,
		arg.Voice,
		arg.Speed,
		arg.Pitch,
		arg.Emotion,
		arg.TotalChunks,
		arg.Text,
	)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.Pitch,
		&i.Emotion,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const ensureTTSJob = `-- name: EnsureTTSJob :one
INSERT INTO tts_jobs (id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET id = tts_jobs.id
RETURNING user_id
`

type EnsureTTSJobParams struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	Engine      string        `json:"engine"`
	Voice       string        `json:"voice"`
	Speed       float64       `json:"speed"`
	Pitch       pgtype.Float8 `json:"pitch"`
	Emotion     pgtype.Text   `json:"emotion"`
	TotalChunks int32         `json:"total_chunks"`
	Text        string        `json:"text"`
}

// EnsureTTSJob creates a job if it does not exist yet, and returns the true owner.
//
// Replaces the GetTTSJobByID-then-CreateTTSJob pair: the first two chunks of the same job arriving
// concurrently both see "not exists" and both try to insert, and the loser silently drops the error.
// A single statement both races and saves a round-trip to the database on each chunk's path.
//
// DO UPDATE ... id = tts_jobs.id rather than DO NOTHING: job_id is sent by the client, so the caller
// must know whether an existing job belongs to them. DO NOTHING returns no row on conflict, so it
// cannot distinguish "just created" from "already owned by someone else" — and the caller would insert
// its chunk into someone else's job unknowingly. A dummy field write ensures RETURNING always has a row.
func (q *Queries) EnsureTTSJob(ctx context.Context, arg EnsureTTSJobParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureTTSJob,
		arg.ID,
		arg.UserID,
		arg.Engine,
		arg.Voice,
		arg.Speed,
		arg.Pitch,
		arg.Emotion,
		arg.TotalChunks,
		arg.Text,
	)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getTTSJobByID = `-- name: GetTTSJobByID :one
SELECT id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text, created_at FROM tts_jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTTSJobByID(ctx context.Context, id string) (TtsJob, error) {
	row := q.db.QueryRow(ctx, getTTSJobByID, id)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.Pitch,
		&i.Emotion,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listUserHistorySummaries = `-- name: ListUserHistorySummaries :many
SELECT
    j.id AS job_id,
    j.engine,
    j.voice,
    j.speed,
    j.total_chunks,
    j.text AS job_text,
    j.created_at,
    COALESCE(COUNT(DISTINCT CASE WHEN c.status = 'done' THEN c.chunk_index END), 0)::int AS done_chunks,
    COALESCE(COUNT(DISTINCT c.chunk_index), 0)::int AS actual_chunks_count,
    COALESCE(MIN(c.text), '')::text AS first_chunk_text
FROM tts_jobs j
LEFT JOIN tts_chunks c ON j.id = c.job_id
WHERE j.user_id = $1
  AND ($3::timestamptz IS NULL
       OR j.created_at < $3::timestamptz
       OR (j.created_at = $3::timestamptz AND j.id < $4::text))
GROUP BY j.id
ORDER BY j.created_at DESC, j.id DESC
LIMIT $2
`

type ListUserHistorySummariesParams struct {
	UserID          string             `json:"user_id"`
	Limit           int32              `json:"limit"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        string             `json:"before_id"`
}

type ListUserHistorySummariesRow struct {
	JobID             string             `json:"job_id"`
	Engine            string             `json:"engine"`
	Voice             string             `json:"voice"`
	Speed             float64            `json:"speed"`
	TotalChunks       int32              `json:"total_chunks"`
	JobText           string             `json:"job_text"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DoneChunks        int32              `json:"done_chunks"`
	ActualChunksCount int32              `json:"actual_chunks_count"`
	FirstChunkText    string             `json:"first_chunk_text"`
}

// ListUserHistorySummaries fetches one page of history, newest first.
//
// Has a LIMIT because the query previously returned every job for a user: heavy users would cause
// each history page open to aggregate and transmit thousands of rows while the UI only shows a subset.
//
// Keyset pagination instead of OFFSET: the next page passes the `before_id` of the last item on the
// previous page along with its `created_at`. The comparison condition (created_at, id) follows the
// ORDER BY order so the planner can use the index instead of scanning excess rows; OFFSET requires
// re-skipping more rows the deeper you page. `before_created_at` accepts NULL for the "first page"
// — the clause falls into the first branch then and filters nothing. The next page is only valid
// when both columns are provided (before_id is a tiebreaker for duplicate timestamps).
//
// GROUP BY j.id: multiple chunks belong to the same job when workers split them — flattened into
// one summary row.
func (q *Queries) ListUserHistorySummaries(ctx context.Context, arg ListUserHistorySummariesParams) ([]ListUserHistorySummariesRow, error) {
	rows, err := q.db.Query(ctx, listUserHistorySummaries,
		arg.UserID,
		arg.Limit,
		arg.BeforeCreatedAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserHistorySummariesRow{}
	for rows.Next() {
		var i ListUserHistorySummariesRow
		if err := rows.Scan(
			&i.JobID,
			&i.Engine,
			&i.Voice,
			&i.Speed,
			&i.TotalChunks,
			&i.JobText,
			&i.CreatedAt,
			&i.DoneChunks,
			&i.ActualChunksCount,
			&i.FirstChunkText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
