// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTTSJob = `-- name: CreateTTSJob :one
INSERT INTO tts_jobs (id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text, created_at
`

type CreateTTSJobParams struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	Engine      string        `json:"engine"`
	Voice       string        `json:"voice"`
	Speed       float64       `json:"speed"`
	Pitch       pgtype.Float8 `json:"pitch"`
	Emotion     pgtype.Text   `json:"emotion"`
	TotalChunks int32         `json:"total_chunks"`
	Text        string        `json:"text"`
}

func (q *Queries) CreateTTSJob(ctx context.Context, arg CreateTTSJobParams) (TtsJob, error) {
	row := q.db.QueryRow(ctx, createTTSJob,
		arg.ID,
		arg.UserID,
		arg.Engine,
		arg.Voice,
		arg.Speed,
		arg.Pitch,
		arg.Emotion,
		arg.TotalChunks,
		arg.Text,
	)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.Pitch,
		&i.Emotion,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const ensureTTSJob = `-- name: EnsureTTSJob :one
INSERT INTO tts_jobs (id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET id = tts_jobs.id
RETURNING user_id
`

type EnsureTTSJobParams struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	Engine      string        `json:"engine"`
	Voice       string        `json:"voice"`
	Speed       float64       `json:"speed"`
	Pitch       pgtype.Float8 `json:"pitch"`
	Emotion     pgtype.Text   `json:"emotion"`
	TotalChunks int32         `json:"total_chunks"`
	Text        string        `json:"text"`
}

// EnsureTTSJob tạo job nếu chưa có, và trả về chủ sở hữu thật của nó.
//
// Thay cho cặp GetTTSJobByID-rồi-CreateTTSJob: hai chunk đầu tiên của cùng một job tới song
// song đều thấy "chưa tồn tại" rồi cùng chèn, và cái thua bị bỏ lỗi âm thầm. Một câu lệnh
// vừa hết đua vừa bớt một lượt đi lại tới cơ sở dữ liệu trên đường đi của mỗi chunk.
//
// DO UPDATE ... id = tts_jobs.id chứ không DO NOTHING: job_id do client gửi lên, nên người
// gọi phải biết được job đã tồn tại là của ai. DO NOTHING không trả dòng nào khi trùng, nên
// không phân biệt được "vừa tạo" với "đã có của người khác" — và người gọi chèn chunk của
// mình vào job của người khác mà không hay. Ghi giả một trường để RETURNING luôn có dòng.
func (q *Queries) EnsureTTSJob(ctx context.Context, arg EnsureTTSJobParams) (string, error) {
	row := q.db.QueryRow(ctx, ensureTTSJob,
		arg.ID,
		arg.UserID,
		arg.Engine,
		arg.Voice,
		arg.Speed,
		arg.Pitch,
		arg.Emotion,
		arg.TotalChunks,
		arg.Text,
	)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getTTSJobByID = `-- name: GetTTSJobByID :one
SELECT id, user_id, engine, voice, speed, pitch, emotion, total_chunks, text, created_at FROM tts_jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTTSJobByID(ctx context.Context, id string) (TtsJob, error) {
	row := q.db.QueryRow(ctx, getTTSJobByID, id)
	var i TtsJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Engine,
		&i.Voice,
		&i.Speed,
		&i.Pitch,
		&i.Emotion,
		&i.TotalChunks,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listUserHistorySummaries = `-- name: ListUserHistorySummaries :many
SELECT
    j.id AS job_id,
    j.engine,
    j.voice,
    j.speed,
    j.total_chunks,
    j.text AS job_text,
    j.created_at,
    COALESCE(COUNT(DISTINCT CASE WHEN c.status = 'done' THEN c.chunk_index END), 0)::int AS done_chunks,
    COALESCE(COUNT(DISTINCT c.chunk_index), 0)::int AS actual_chunks_count,
    COALESCE(MIN(c.text), '')::text AS first_chunk_text
FROM tts_jobs j
LEFT JOIN tts_chunks c ON j.id = c.job_id
WHERE j.user_id = $1
  AND ($3::timestamptz IS NULL
       OR j.created_at < $3::timestamptz
       OR (j.created_at = $3::timestamptz AND j.id < $4::text))
GROUP BY j.id
ORDER BY j.created_at DESC, j.id DESC
LIMIT $2
`

type ListUserHistorySummariesParams struct {
	UserID          string             `json:"user_id"`
	Limit           int32              `json:"limit"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        string             `json:"before_id"`
}

type ListUserHistorySummariesRow struct {
	JobID             string             `json:"job_id"`
	Engine            string             `json:"engine"`
	Voice             string             `json:"voice"`
	Speed             float64            `json:"speed"`
	TotalChunks       int32              `json:"total_chunks"`
	JobText           string             `json:"job_text"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DoneChunks        int32              `json:"done_chunks"`
	ActualChunksCount int32              `json:"actual_chunks_count"`
	FirstChunkText    string             `json:"first_chunk_text"`
}

// ListUserHistorySummaries lấy một trang lịch sử, mới nhất trước.
//
// Có LIMIT vì trước đây truy vấn trả về mọi job của người dùng: ai dùng nhiều thì mỗi lần
// mở lịch sử là tổng hợp rồi truyền về hàng nghìn dòng mà giao diện chỉ hiển thị một phần.
//
// Phân trang theo con trỏ (keyset) thay vì OFFSET: trang kế tiếp truyền `before_id` của item
// cuối cùng trang trước cùng `created_at` của nó. Điều kiện so sánh (created_at, id) theo thứ
// tự của ORDER BY nên bộ lập kế hoạch dùng được chỉ mục thay vì quét dòng thừa; OFFSET thì
// mỗi trang sâu thêm một nấc phải bỏ đi lại càng nhiều dòng. `before_created_at` nhận NULL
// cho "trang đầu" — lúc đó mệnh đề rơi vào nhánh đầu nên không lọc gì. Trang tiếp theo chỉ
// có giá trị khi hai cột cùng được truyền (before_id là cột phụ để chống trùng timestamp).
//
// GROUP BY j.id: nhiều chunk nằm trong cùng một job khi tách chạy worker — tôi cần làm phẳng
// chúng ra một hàng summary.
func (q *Queries) ListUserHistorySummaries(ctx context.Context, arg ListUserHistorySummariesParams) ([]ListUserHistorySummariesRow, error) {
	rows, err := q.db.Query(ctx, listUserHistorySummaries,
		arg.UserID,
		arg.Limit,
		arg.BeforeCreatedAt,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserHistorySummariesRow{}
	for rows.Next() {
		var i ListUserHistorySummariesRow
		if err := rows.Scan(
			&i.JobID,
			&i.Engine,
			&i.Voice,
			&i.Speed,
			&i.TotalChunks,
			&i.JobText,
			&i.CreatedAt,
			&i.DoneChunks,
			&i.ActualChunksCount,
			&i.FirstChunkText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
