// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (id, session_family_id, user_id, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, session_family_id, user_id, created_at, expires_at, revoked_at, replaced_by, user_agent, ip
`

type CreateAuthSessionParams struct {
	ID              string             `json:"id"`
	SessionFamilyID string             `json:"session_family_id"`
	UserID          string             `json:"user_id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UserAgent       pgtype.Text        `json:"user_agent"`
	Ip              pgtype.Text        `json:"ip"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.ID,
		arg.SessionFamilyID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.SessionFamilyID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :execrows
DELETE FROM auth_sessions
WHERE expires_at < CURRENT_TIMESTAMP
`

// Clean up expired sessions. Called opportunistically at login: small table, DELETE by index,
// no need for a separate cleanup process.
func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT id, session_family_id, user_id, created_at, expires_at, revoked_at, replaced_by, user_agent, ip FROM auth_sessions
WHERE id = $1
`

func (q *Queries) GetAuthSession(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSession, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.SessionFamilyID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND revoked_at IS NULL
`

// Logout: revoke the current token. Do not set replaced_by, so every other token in the same family
// (already revoked+replaced or this token itself) has no representative left for the session — the session is dead.
func (q *Queries) RevokeAuthSession(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAuthSessionFamily = `-- name: RevokeAuthSessionFamily :execrows
UPDATE auth_sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE session_family_id = $1
  AND revoked_at IS NULL
`

// Revoke all living tokens in the family. Used when an old token reuse is detected (stolen token):
// the family is taken down, and the user must log in again.
func (q *Queries) RevokeAuthSessionFamily(ctx context.Context, sessionFamilyID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSessionFamily, sessionFamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :execrows
UPDATE auth_sessions
SET revoked_at = CURRENT_TIMESTAMP,
    replaced_by = $2
WHERE id = $1
  AND revoked_at IS NULL
`

type RotateAuthSessionParams struct {
	ID         string      `json:"id"`
	ReplacedBy pgtype.Text `json:"replaced_by"`
}

// Mark the old token as replaced by the new token in the same family (rotation).
// Guard revoked_at IS NULL: if the session has already been revoked (logout, family revoke), do not overwrite replaced_by.
func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateAuthSession, arg.ID, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
