// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voices.sql

package sqlc

import (
	"context"
)

const createUserVoice = `-- name: CreateUserVoice :one
INSERT INTO user_voices (id, user_id, model_id, name, file_path, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, model_id, name, file_path, metadata, created_at
`

type CreateUserVoiceParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	ModelID  string `json:"model_id"`
	Name     string `json:"name"`
	FilePath string `json:"file_path"`
	Metadata []byte `json:"metadata"`
}

func (q *Queries) CreateUserVoice(ctx context.Context, arg CreateUserVoiceParams) (UserVoice, error) {
	row := q.db.QueryRow(ctx, createUserVoice,
		arg.ID,
		arg.UserID,
		arg.ModelID,
		arg.Name,
		arg.FilePath,
		arg.Metadata,
	)
	var i UserVoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModelID,
		&i.Name,
		&i.FilePath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserVoice = `-- name: DeleteUserVoice :exec
DELETE FROM user_voices
WHERE id = $1 AND user_id = $2
`

type DeleteUserVoiceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteUserVoice(ctx context.Context, arg DeleteUserVoiceParams) error {
	_, err := q.db.Exec(ctx, deleteUserVoice, arg.ID, arg.UserID)
	return err
}

const getUserVoiceByID = `-- name: GetUserVoiceByID :one
SELECT id, user_id, model_id, name, file_path, metadata, created_at FROM user_voices
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetUserVoiceByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetUserVoiceByID(ctx context.Context, arg GetUserVoiceByIDParams) (UserVoice, error) {
	row := q.db.QueryRow(ctx, getUserVoiceByID, arg.ID, arg.UserID)
	var i UserVoice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModelID,
		&i.Name,
		&i.FilePath,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listUserVoices = `-- name: ListUserVoices :many
SELECT id, user_id, model_id, name, file_path, metadata, created_at FROM user_voices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserVoices(ctx context.Context, userID string) ([]UserVoice, error) {
	rows, err := q.db.Query(ctx, listUserVoices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserVoice{}
	for rows.Next() {
		var i UserVoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModelID,
			&i.Name,
			&i.FilePath,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVoicesByModel = `-- name: ListUserVoicesByModel :many
SELECT id, user_id, model_id, name, file_path, metadata, created_at FROM user_voices
WHERE user_id = $1 AND model_id = $2
ORDER BY created_at DESC
`

type ListUserVoicesByModelParams struct {
	UserID  string `json:"user_id"`
	ModelID string `json:"model_id"`
}

func (q *Queries) ListUserVoicesByModel(ctx context.Context, arg ListUserVoicesByModelParams) ([]UserVoice, error) {
	rows, err := q.db.Query(ctx, listUserVoicesByModel, arg.UserID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserVoice{}
	for rows.Next() {
		var i UserVoice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModelID,
			&i.Name,
			&i.FilePath,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
