# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import tts_pb2 as proto_dot_tts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/tts.TTSService/GetInfo',
                request_serializer=proto_dot_tts__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.GetInfoResponse.FromString,
                _registered_method=True)
        self.GetVoices = channel.unary_unary(
                '/tts.TTSService/GetVoices',
                request_serializer=proto_dot_tts__pb2.GetVoicesRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.GetVoicesResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/tts.TTSService/Synthesize',
                request_serializer=proto_dot_tts__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.SynthesizeResponse.FromString,
                _registered_method=True)
        self.CloneVoice = channel.unary_unary(
                '/tts.TTSService/CloneVoice',
                request_serializer=proto_dot_tts__pb2.CloneVoiceRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.CloneVoiceResponse.FromString,
                _registered_method=True)


class TTSServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloneVoice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=proto_dot_tts__pb2.GetInfoRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.GetInfoResponse.SerializeToString,
            ),
            'GetVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVoices,
                    request_deserializer=proto_dot_tts__pb2.GetVoicesRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.GetVoicesResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=proto_dot_tts__pb2.SynthesizeRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.SynthesizeResponse.SerializeToString,
            ),
            'CloneVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.CloneVoice,
                    request_deserializer=proto_dot_tts__pb2.CloneVoiceRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.CloneVoiceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/GetInfo',
            proto_dot_tts__pb2.GetInfoRequest.SerializeToString,
            proto_dot_tts__pb2.GetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/GetVoices',
            proto_dot_tts__pb2.GetVoicesRequest.SerializeToString,
            proto_dot_tts__pb2.GetVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/Synthesize',
            proto_dot_tts__pb2.SynthesizeRequest.SerializeToString,
            proto_dot_tts__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloneVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TTSService/CloneVoice',
            proto_dot_tts__pb2.CloneVoiceRequest.SerializeToString,
            proto_dot_tts__pb2.CloneVoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
