# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tts.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/tts.proto\x12\x03tts\"\x10\n\x0eGetInfoRequest\"(\n\x0fGetInfoResponse\x12\x15\n\rmanifest_json\x18\x01 \x01(\t\"6\n\x10GetVoicesRequest\x12\x15\n\x08model_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_model_id\"J\n\tVoiceInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65scriptions\x18\x03 \x03(\t\x12\r\n\x05modes\x18\x04 \x03(\t\"3\n\x11GetVoicesResponse\x12\x1e\n\x06voices\x18\x01 \x03(\x0b\x32\x0e.tts.VoiceInfo\"\x92\x01\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x01\x12\x0e\n\x06\x65ngine\x18\x04 \x01(\t\x12\x12\n\x05pitch\x18\x05 \x01(\x01H\x00\x88\x01\x01\x12\x14\n\x07\x65motion\x18\x06 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06_pitchB\n\n\x08_emotion\"<\n\x12SynthesizeResponse\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x12\x11\n\terror_msg\x18\x02 \x01(\t\"F\n\x11\x43loneVoiceRequest\x12\x13\n\x0b\x61udio_bytes\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x03 \x01(\t\"W\n\x12\x43loneVoiceResponse\x12\x10\n\x08voice_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\terror_msg\x18\x04 \x01(\t2\xfc\x01\n\nTTSService\x12\x34\n\x07GetInfo\x12\x13.tts.GetInfoRequest\x1a\x14.tts.GetInfoResponse\x12:\n\tGetVoices\x12\x15.tts.GetVoicesRequest\x1a\x16.tts.GetVoicesResponse\x12=\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse\x12=\n\nCloneVoice\x12\x16.tts.CloneVoiceRequest\x1a\x17.tts.CloneVoiceResponseB\x0fZ\rbackend/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rbackend/proto'
  _globals['_GETINFOREQUEST']._serialized_start=24
  _globals['_GETINFOREQUEST']._serialized_end=40
  _globals['_GETINFORESPONSE']._serialized_start=42
  _globals['_GETINFORESPONSE']._serialized_end=82
  _globals['_GETVOICESREQUEST']._serialized_start=84
  _globals['_GETVOICESREQUEST']._serialized_end=138
  _globals['_VOICEINFO']._serialized_start=140
  _globals['_VOICEINFO']._serialized_end=214
  _globals['_GETVOICESRESPONSE']._serialized_start=216
  _globals['_GETVOICESRESPONSE']._serialized_end=267
  _globals['_SYNTHESIZEREQUEST']._serialized_start=270
  _globals['_SYNTHESIZEREQUEST']._serialized_end=416
  _globals['_SYNTHESIZERESPONSE']._serialized_start=418
  _globals['_SYNTHESIZERESPONSE']._serialized_end=478
  _globals['_CLONEVOICEREQUEST']._serialized_start=480
  _globals['_CLONEVOICEREQUEST']._serialized_end=550
  _globals['_CLONEVOICERESPONSE']._serialized_start=552
  _globals['_CLONEVOICERESPONSE']._serialized_end=639
  _globals['_TTSSERVICE']._serialized_start=642
  _globals['_TTSSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
