# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tts.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/tts.proto\x12\x03tts\"@\n\x12StandardTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x01\"X\n\x0f\x43loneTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0eref_audio_path\x18\x02 \x01(\t\x12\x10\n\x08ref_text\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x01\"<\n\x0e\x46\x61stTTSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\r\n\x05speed\x18\x03 \x01(\x01\"\x89\x01\n\x10TTSChunkResponse\x12\x13\n\x0b\x63hunk_index\x18\x01 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x05\x12\x13\n\x0b\x61udio_bytes\x18\x03 \x01(\x0c\x12\x12\n\naudio_path\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x11\n\terror_msg\x18\x06 \x01(\t2\xd6\x01\n\nTTSService\x12\x46\n\x12SynthesizeStandard\x12\x17.tts.StandardTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01\x12@\n\x0fSynthesizeClone\x12\x14.tts.CloneTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01\x12>\n\x0eSynthesizeFast\x12\x13.tts.FastTTSRequest\x1a\x15.tts.TTSChunkResponse0\x01\x42\x18Z\x16\x63ore-backend/proto/ttsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026core-backend/proto/tts'
  _globals['_STANDARDTTSREQUEST']._serialized_start=24
  _globals['_STANDARDTTSREQUEST']._serialized_end=88
  _globals['_CLONETTSREQUEST']._serialized_start=90
  _globals['_CLONETTSREQUEST']._serialized_end=178
  _globals['_FASTTTSREQUEST']._serialized_start=180
  _globals['_FASTTTSREQUEST']._serialized_end=240
  _globals['_TTSCHUNKRESPONSE']._serialized_start=243
  _globals['_TTSCHUNKRESPONSE']._serialized_end=380
  _globals['_TTSSERVICE']._serialized_start=383
  _globals['_TTSSERVICE']._serialized_end=597
# @@protoc_insertion_point(module_scope)
