# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import tts_pb2 as proto_dot_tts__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TTSServiceStub:
    """Service giao tiếp TTS cao cấp giữa Go Core-Backend và Python Core-TTS Engine
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeStandard = channel.unary_stream(
                '/tts.TTSService/SynthesizeStandard',
                request_serializer=proto_dot_tts__pb2.StandardTTSRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.TTSChunkResponse.FromString,
                _registered_method=True)
        self.SynthesizeClone = channel.unary_stream(
                '/tts.TTSService/SynthesizeClone',
                request_serializer=proto_dot_tts__pb2.CloneTTSRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.TTSChunkResponse.FromString,
                _registered_method=True)
        self.SynthesizeFast = channel.unary_stream(
                '/tts.TTSService/SynthesizeFast',
                request_serializer=proto_dot_tts__pb2.FastTTSRequest.SerializeToString,
                response_deserializer=proto_dot_tts__pb2.TTSChunkResponse.FromString,
                _registered_method=True)


class TTSServiceServicer:
    """Service giao tiếp TTS cao cấp giữa Go Core-Backend và Python Core-TTS Engine
    """

    def SynthesizeStandard(self, request, context):
        """SynthesizeStandard stream các đoạn audio tổng hợp chuẩn theo thời gian thực (Server Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeClone(self, request, context):
        """SynthesizeClone stream các đoạn audio nhân bản giọng nói (Voice Cloning) thời gian thực
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SynthesizeFast(self, request, context):
        """SynthesizeFast stream các đoạn audio tốc độ cao (Fast Engine) thời gian thực
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeStandard': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStandard,
                    request_deserializer=proto_dot_tts__pb2.StandardTTSRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.TTSChunkResponse.SerializeToString,
            ),
            'SynthesizeClone': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeClone,
                    request_deserializer=proto_dot_tts__pb2.CloneTTSRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.TTSChunkResponse.SerializeToString,
            ),
            'SynthesizeFast': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeFast,
                    request_deserializer=proto_dot_tts__pb2.FastTTSRequest.FromString,
                    response_serializer=proto_dot_tts__pb2.TTSChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService:
    """Service giao tiếp TTS cao cấp giữa Go Core-Backend và Python Core-TTS Engine
    """

    @staticmethod
    def SynthesizeStandard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSService/SynthesizeStandard',
            proto_dot_tts__pb2.StandardTTSRequest.SerializeToString,
            proto_dot_tts__pb2.TTSChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeClone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSService/SynthesizeClone',
            proto_dot_tts__pb2.CloneTTSRequest.SerializeToString,
            proto_dot_tts__pb2.TTSChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SynthesizeFast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tts.TTSService/SynthesizeFast',
            proto_dot_tts__pb2.FastTTSRequest.SerializeToString,
            proto_dot_tts__pb2.TTSChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
